import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Route, Routes } from 'react-router';
import './index.css';
import RootPage from './pages/(root)/page';
import DashboardPage from './pages/dashboard/page';
import DashboardLayout from './pages/dashboard/layout';
import AdminMQTTBrokerPage from './pages/dashboard/admin/mqtt-broker/page';
import AdminLayout from './pages/dashboard/admin/layout';
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { index: true, element: _jsx(RootPage, {}) }), _jsxs(Route, { path: "dashboard", element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "admin", element: _jsx(AdminLayout, {}), children: _jsx(Route, { path: "mqtt-broker", element: _jsx(AdminMQTTBrokerPage, {}) }) })] })] }) }) }));
